# Generated by Django 3.1.7 on 2021-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(default=999, max_length=100),
            preserve_default=False,
        ),
    ]
