# Generated by Django 3.1.7 on 2021-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_auto_20210323_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='biography',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
