# Generated by Django 3.1.7 on 2021-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0007_myuser_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_logon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
