# Generated by Django 3.1.7 on 2021-03-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0008_auto_20210323_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
