# Generated by Django 3.1.7 on 2021-03-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0014_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('address_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=True)),
                ('address_created_time', models.DateTimeField(auto_now_add=True)),
                ('address_updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
        ),
    ]
