# Generated by Django 3.1.7 on 2021-04-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0015_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
