# Generated by Django 3.1.7 on 2021-04-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0017_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='myuser_foreign',
        ),
    ]
