# Generated by Django 3.1.7 on 2021-04-18 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0018_auto_20210401_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigations',
            fields=[
                ('navigation_id', models.AutoField(primary_key=True, serialize=False)),
                ('navigation_name', models.CharField(max_length=20)),
                ('start_address', models.CharField(max_length=44)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('goal_address', models.FloatField()),
                ('goal_lat', models.FloatField()),
                ('goal_lng', models.FloatField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=True)),
                ('myuser_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
