# Generated by Django 3.1.7 on 2021-04-18 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0019_navigations'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigations',
            name='navigations_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigations',
            name='navigations_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
