# Generated by Django 3.1.7 on 2021-04-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0020_auto_20210418_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigations',
            name='goal_address',
            field=models.CharField(max_length=44),
        ),
    ]
